### ISSUE TITLE
单词表页面发现错误

### ISSUE THREAD

**Issue by beijiahiddink** [wizicer/LearnJapan#11]
在页面<http://japan.icerdesign.com/tools/wordlist.html>发现错误。
错误是：はがき 音调标注不对啊，单词其他地方是不是也有这种问题啊

**Comment by wizicer** [comment]
单词表里面的音标是我上课时一个一个对过的，但人工难免有疏漏，不排除有错误的可能性。

你这个是哪个单词标错了？按照`はがき`我搜不到。

**Comment by wizicer** [comment]
No response, so close the issue.
